const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Orbit,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Tilemap,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Acts.SaveState,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Audio.Acts.PlayAtPosition,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Behaviors.Orbit.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.AddConvolutionEffect,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Behaviors.Bullet.Cnds.OnStep,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Bullet.Exps.Acceleration,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Height
	];
};
self.C3_JsPropNameTable = [
	{Flash: 0},
	{MoveTo: 0},
	{Sine: 0},
	{Blub: 0},
	{Blueberry: 0},
	{CandyKnight: 0},
	{CandyNPC: 0},
	{CandyNPC2: 0},
	{CandyNPC3: 0},
	{CribNPC: 0},
	{CribNPC2: 0},
	{Dozer: 0},
	{Elyssa: 0},
	{Fade: 0},
	{glormbus: 0},
	{Huxley: 0},
	{KhiliPepper: 0},
	{Kiosk: 0},
	{Lolipop: 0},
	{Mallium: 0},
	{Polaris: 0},
	{Squirt: 0},
	{Waiter: 0},
	{Warden: 0},
	{WcDonaldsNPC: 0},
	{WcDonaldsNPC2: 0},
	{Wilson: 0},
	{Akumu: 0},
	{Sine2: 0},
	{guard1: 0},
	{Kari: 0},
	{guard2: 0},
	{guard3: 0},
	{guard4: 0},
	{guard5: 0},
	{Scarbie: 0},
	{Panopticon: 0},
	{Cherry: 0},
	{Aoi: 0},
	{James: 0},
	{James2: 0},
	{DialogueStage: 0},
	{SpObj1: 0},
	{SpObj2: 0},
	{SpObj3: 0},
	{SpObj4: 0},
	{SpObj5: 0},
	{SpObj6: 0},
	{SpObj7: 0},
	{SpObj8: 0},
	{Akumu2: 0},
	{Akumu3: 0},
	{Kari2: 0},
	{Odette: 0},
	{FunnyChef: 0},
	{Ru: 0},
	{Bookwyrm: 0},
	{Owl: 0},
	{Doug: 0},
	{Bartholomew: 0},
	{Akhet: 0},
	{SmokeDetector: 0},
	{Sine3: 0},
	{NUMNOTFOUND: 0},
	{HeadChef: 0},
	{Cookie: 0},
	{Pumkin: 0},
	{Floater: 0},
	{FloaterInteract: 0},
	{Eraser1: 0},
	{Eraser2: 0},
	{Eraser3: 0},
	{Artkit: 0},
	{Wym: 0},
	{Frank: 0},
	{Womp: 0},
	{Blub2: 0},
	{Luvy: 0},
	{ActionFigure: 0},
	{ActionFigure2: 0},
	{InvisInteract1: 0},
	{InvisInteract2: 0},
	{InvisInteract3: 0},
	{MenuTXT: 0},
	{PRESSZTOSTART: 0},
	{Logo: 0},
	{IntroTXT: 0},
	{WhiteFade: 0},
	{TextBox: 0},
	{DialogueTXT: 0},
	{BlackFade: 0},
	{Z: 0},
	{Black: 0},
	{TextBox2: 0},
	{DialogueTXT2: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{AlliumPlayer: 0},
	{AlliumBattle: 0},
	{MipArcade: 0},
	{BattleBKG: 0},
	{BattleBKG2: 0},
	{MHPBarBKG: 0},
	{MHPBar: 0},
	{BattleTXT: 0},
	{MHPCount: 0},
	{EnemyHPBarBKG: 0},
	{EnemyHPBar: 0},
	{EnemyHeart: 0},
	{HP: 0},
	{Solid: 0},
	{Orbit: 0},
	{EnemyBarrier: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{EnemyBullet: 0},
	{EnemyTurret: 0},
	{PlayerTurret: 0},
	{PlayerBullet: 0},
	{BlackFadeBattle: 0},
	{EnemyBullet2: 0},
	{EnemyBullet3: 0},
	{EnemyBullet4: 0},
	{EnemyBullet5: 0},
	{EnemyBullet6: 0},
	{ArcadeBullet: 0},
	{ArcadeEnemyBullet: 0},
	{HighCount: 0},
	{PlayerTurretEcho: 0},
	{ArcadeParryBullet: 0},
	{BattleSpotlight: 0},
	{EnemyBullet7: 0},
	{Aimer: 0},
	{EnemyBullet7Echo: 0},
	{EnemyBullet8: 0},
	{EnemyHeart2: 0},
	{EnemyBullet9: 0},
	{AkumuBattleSpotlight: 0},
	{PongPointCount: 0},
	{PlayerPong: 0},
	{EnemyPong: 0},
	{PongBullet: 0},
	{pointforplayer: 0},
	{pointforenemy: 0},
	{EnemyHeart3: 0},
	{TurArrowUp: 0},
	{TurArrowDown: 0},
	{TurArrowRight: 0},
	{TurArrowLeft: 0},
	{EnemyBullet10: 0},
	{EnemyBullet11: 0},
	{EnemyBullet12: 0},
	{EnemyBullet13: 0},
	{BattleTXT2: 0},
	{EnemyBullet14: 0},
	{PongBullet2: 0},
	{greenshield: 0},
	{EnemyBullet15: 0},
	{Aimer2: 0},
	{AkumuBattleSpotlight2: 0},
	{EnemyBullet16: 0},
	{TurArrowDown2: 0},
	{TurArrowLeft2: 0},
	{TurArrowRight2: 0},
	{TurArrowUp2: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Door: 0},
	{Trigger: 0},
	{Border: 0},
	{Tilemap: 0},
	{Warp: 0},
	{sweetSand: 0},
	{WcDonaldsBKG: 0},
	{feathers: 0},
	{FurryWorldBKG: 0},
	{AlliumPic: 0},
	{huxleyparticles: 0},
	{Particles: 0},
	{centerbox: 0},
	{darkspotlight: 0},
	{darkgradient: 0},
	{arcade: 0},
	{REDDEATH: 0},
	{original: 0},
	{deltaexplosion: 0},
	{ElyssaRoomBKG: 0},
	{catbed: 0},
	{PingPongTable: 0},
	{PingPongBKG: 0},
	{CafeteriaTables: 0},
	{MessHallTable: 0},
	{toaster: 0},
	{evildeathbattle: 0},
	{deadcloversigilbook: 0},
	{holeinwall: 0},
	{holeinwall2: 0},
	{tallgrass: 0},
	{LaserLine: 0},
	{trashcan: 0},
	{toilet: 0},
	{LaserLine2: 0},
	{Particles2: 0},
	{knive: 0},
	{noise: 0},
	{GameOverQuote: 0},
	{LetSAVEPressZ: 0},
	{LetNPCPressZ1: 0},
	{LetNPCPressZ2: 0},
	{LetNPCPressZ3: 0},
	{SAVEDialogueStage: 0},
	{NPCDialogueStage: 0},
	{ElyssaCutsceneDone: 0},
	{LolipopCutsceneDone: 0},
	{HuxleyCutsceneDone: 0},
	{KnightCutsceneDone: 0},
	{KnightCutsceneDone2: 0},
	{GlormbusCutsceneDone: 0},
	{LolipopBattleCutsceneDone: 0},
	{CarnivalCutsceneDone: 0},
	{CarnivalCutsceneDone2: 0},
	{CribCutsceneDone: 0},
	{CribCutsceneDone2: 0},
	{CribCutsceneDone3: 0},
	{CribCutsceneDone4: 0},
	{MovementAllow: 0},
	{CutsceneDialogueStage: 0},
	{CutsceneLetPressZ: 0},
	{DVCutscene1Done: 0},
	{DVCutscene2Done: 0},
	{triggeredDV2: 0},
	{AlliumX: 0},
	{AlliumY: 0},
	{DVCutscene3Done: 0},
	{DVCutscene4Done: 0},
	{FurryWorldCutsceneDone: 0},
	{FurryWorldCutsceneDone2: 0},
	{FurryWorldCutsceneDone3: 0},
	{FurryWorldCutsceneDone4: 0},
	{WcDonaldsCutsceneDone: 0},
	{WcDonaldsCutsceneDone2: 0},
	{WcDonaldsCutsceneDone3: 0},
	{WcDonaldsCutsceneDone4: 0},
	{AkumuCutscene1Done: 0},
	{v2karifinalcutscene2: 0},
	{randomGuardEncounter: 0},
	{ElyssaV2Cutscene: 0},
	{ArcadeLetPressZ: 0},
	{PrevLayout: 0},
	{AkumuCutscene3Done: 0},
	{KariCutscene: 0},
	{KariCutscene2: 0},
	{randomGuardEncounter2: 0},
	{ScarbieCutscene1: 0},
	{ScarbieCutscene2: 0},
	{ScarbieCutscene3: 0},
	{AkariCutscene1: 0},
	{panopticoncutscene: 0},
	{cherrycutscenedone: 0},
	{CherryCutscene2: 0},
	{fruitfrensCutscene: 0},
	{aoicutscene1: 0},
	{AoiCutscene2: 0},
	{AoiCutscene3: 0},
	{AkariCutscene2: 0},
	{jamescutscene: 0},
	{akumubetraycutscene: 0},
	{v2WardenAgainCutscene: 0},
	{v2KariFinalCutscene: 0},
	{AkumuCutscene2Done2: 0},
	{HallwayCutsceneDone1: 0},
	{HallwayCutsceneDone2: 0},
	{ElyssaRoomCutscene1: 0},
	{ElyssaRoomCutscene2: 0},
	{HallwayCutsceneDone3: 0},
	{MessHallCutsceneDone1: 0},
	{MessHallCutsceneDone2: 0},
	{HallwayCutsceneDone4: 0},
	{HallwayCutsceneDone5: 0},
	{HallwayCutsceneDone6: 0},
	{HallwayCutsceneDone7: 0},
	{LibraryCutsceneDone1: 0},
	{LibraryCutsceneDone2: 0},
	{LibraryCutsceneDone3: 0},
	{BasementCutsceneDone1: 0},
	{BasementCutsceneDone2: 0},
	{BasementCutsceneDone3: 0},
	{BasementCutsceneDone4: 0},
	{pix: 0},
	{BasementCutsceneDone5: 0},
	{MessHallCutsceneDone3: 0},
	{MessHallCutsceneDone4: 0},
	{MessHallCutsceneDone5: 0},
	{HallwayCutsceneDone8: 0},
	{HallwayCutsceneDone9: 0},
	{BathroomCutsceneDone1: 0},
	{BathroomCutsceneDone2: 0},
	{HallwayCutsceneDone10: 0},
	{HallwayCutsceneDone11: 0},
	{CourtyardCutsceneDone1: 0},
	{CourtyardCutsceneDone2: 0},
	{v3finalcutscenedone: 0},
	{battleTalk: 0},
	{MHP: 0},
	{EnemyMHP: 0},
	{MAXEnemyMHP: 0},
	{BattlePhase: 0},
	{HighScore: 0},
	{isfromArcade: 0},
	{IsDashing: 0},
	{IsParrying: 0},
	{MaxMHP: 0},
	{MaxMHP2: 0},
	{MaxMHP3: 0},
	{MaxMHP4: 0},
	{MaxMHP5: 0},
	{MaxMHP6: 0},
	{EnemyPoints: 0},
	{IsEnemyParrying: 0},
	{PlayerPoints: 0},
	{EnemyPoints2: 0},
	{IsEnemyParrying2: 0},
	{PlayerPoints2: 0},
	{heartside: 0},
	{MaxMHP7: 0},
	{TargetX: 0},
	{TargetY: 0}
];

self.InstanceType = {
	Blub: class extends self.ISpriteInstance {},
	Blueberry: class extends self.ISpriteInstance {},
	CandyKnight: class extends self.ISpriteInstance {},
	CandyNPC: class extends self.ISpriteInstance {},
	CandyNPC2: class extends self.ISpriteInstance {},
	CandyNPC3: class extends self.ISpriteInstance {},
	CribNPC: class extends self.ISpriteInstance {},
	CribNPC2: class extends self.ISpriteInstance {},
	Dozer: class extends self.ISpriteInstance {},
	Elyssa: class extends self.ISpriteInstance {},
	glormbus: class extends self.ISpriteInstance {},
	Huxley: class extends self.ISpriteInstance {},
	KhiliPepper: class extends self.ISpriteInstance {},
	Kiosk: class extends self.ISpriteInstance {},
	Lolipop: class extends self.ISpriteInstance {},
	Mallium: class extends self.ISpriteInstance {},
	Polaris: class extends self.ISpriteInstance {},
	Squirt: class extends self.ISpriteInstance {},
	Waiter: class extends self.ISpriteInstance {},
	Warden: class extends self.ISpriteInstance {},
	WcDonaldsNPC: class extends self.ISpriteInstance {},
	WcDonaldsNPC2: class extends self.ISpriteInstance {},
	Wilson: class extends self.ISpriteInstance {},
	Akumu: class extends self.ISpriteInstance {},
	guard1: class extends self.ISpriteInstance {},
	Kari: class extends self.ISpriteInstance {},
	guard2: class extends self.ISpriteInstance {},
	guard3: class extends self.ISpriteInstance {},
	guard4: class extends self.ISpriteInstance {},
	guard5: class extends self.ISpriteInstance {},
	Scarbie: class extends self.ISpriteInstance {},
	Panopticon: class extends self.ISpriteInstance {},
	Cherry: class extends self.ISpriteInstance {},
	Aoi: class extends self.ISpriteInstance {},
	James: class extends self.ISpriteInstance {},
	James2: class extends self.ISpriteInstance {},
	SpObj1: class extends self.ISpriteInstance {},
	SpObj2: class extends self.ISpriteInstance {},
	SpObj3: class extends self.ISpriteInstance {},
	SpObj4: class extends self.ISpriteInstance {},
	SpObj5: class extends self.ISpriteInstance {},
	SpObj6: class extends self.ISpriteInstance {},
	SpObj7: class extends self.ISpriteInstance {},
	SpObj8: class extends self.ISpriteInstance {},
	Akumu2: class extends self.ISpriteInstance {},
	Akumu3: class extends self.ISpriteInstance {},
	Kari2: class extends self.ISpriteInstance {},
	Odette: class extends self.ISpriteInstance {},
	FunnyChef: class extends self.ISpriteInstance {},
	Ru: class extends self.ISpriteInstance {},
	Bookwyrm: class extends self.ISpriteInstance {},
	Owl: class extends self.ISpriteInstance {},
	Doug: class extends self.ISpriteInstance {},
	Bartholomew: class extends self.ISpriteInstance {},
	Akhet: class extends self.ISpriteInstance {},
	SmokeDetector: class extends self.ISpriteInstance {},
	NUMNOTFOUND: class extends self.ISpriteInstance {},
	HeadChef: class extends self.ISpriteInstance {},
	Cookie: class extends self.ISpriteInstance {},
	Pumkin: class extends self.ISpriteInstance {},
	Floater: class extends self.ISpriteInstance {},
	FloaterInteract: class extends self.ISpriteInstance {},
	Eraser1: class extends self.ISpriteInstance {},
	Eraser2: class extends self.ISpriteInstance {},
	Eraser3: class extends self.ISpriteInstance {},
	Artkit: class extends self.ISpriteInstance {},
	Wym: class extends self.ISpriteInstance {},
	Frank: class extends self.ISpriteInstance {},
	Womp: class extends self.ISpriteInstance {},
	Blub2: class extends self.ISpriteInstance {},
	Luvy: class extends self.ISpriteInstance {},
	ActionFigure: class extends self.ISpriteInstance {},
	ActionFigure2: class extends self.ISpriteInstance {},
	InvisInteract1: class extends self.ISpriteInstance {},
	InvisInteract2: class extends self.ISpriteInstance {},
	InvisInteract3: class extends self.ISpriteInstance {},
	MenuTXT: class extends self.ISpriteFontInstance {},
	PRESSZTOSTART: class extends self.ISpriteFontInstance {},
	Logo: class extends self.ISpriteInstance {},
	IntroTXT: class extends self.ISpriteFontInstance {},
	WhiteFade: class extends self.ISpriteInstance {},
	TextBox: class extends self.ISpriteInstance {},
	DialogueTXT: class extends self.ISpriteFontInstance {},
	BlackFade: class extends self.ISpriteInstance {},
	Z: class extends self.ISpriteFontInstance {},
	Black: class extends self.ISpriteInstance {},
	TextBox2: class extends self.ISpriteInstance {},
	DialogueTXT2: class extends self.ISpriteFontInstance {},
	AlliumPlayer: class extends self.ISpriteInstance {},
	AlliumBattle: class extends self.ISpriteInstance {},
	MipArcade: class extends self.ISpriteInstance {},
	BattleBKG: class extends self.ITiledBackgroundInstance {},
	BattleBKG2: class extends self.ITiledBackgroundInstance {},
	MHPBarBKG: class extends self.ISpriteInstance {},
	MHPBar: class extends self.ISpriteInstance {},
	BattleTXT: class extends self.ISpriteFontInstance {},
	MHPCount: class extends self.ISpriteFontInstance {},
	EnemyHPBarBKG: class extends self.ISpriteInstance {},
	EnemyHPBar: class extends self.ISpriteInstance {},
	EnemyHeart: class extends self.ISpriteInstance {},
	EnemyBarrier: class extends self.ISpriteInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	EnemyTurret: class extends self.ISpriteInstance {},
	PlayerTurret: class extends self.ISpriteInstance {},
	PlayerBullet: class extends self.ISpriteInstance {},
	BlackFadeBattle: class extends self.ISpriteInstance {},
	EnemyBullet2: class extends self.ISpriteInstance {},
	EnemyBullet3: class extends self.ISpriteInstance {},
	EnemyBullet4: class extends self.ISpriteInstance {},
	EnemyBullet5: class extends self.ISpriteInstance {},
	EnemyBullet6: class extends self.ISpriteInstance {},
	ArcadeBullet: class extends self.ISpriteInstance {},
	ArcadeEnemyBullet: class extends self.ISpriteInstance {},
	HighCount: class extends self.ISpriteFontInstance {},
	PlayerTurretEcho: class extends self.ISpriteInstance {},
	ArcadeParryBullet: class extends self.ISpriteInstance {},
	BattleSpotlight: class extends self.ISpriteInstance {},
	EnemyBullet7: class extends self.ISpriteInstance {},
	Aimer: class extends self.ISpriteInstance {},
	EnemyBullet7Echo: class extends self.ISpriteInstance {},
	EnemyBullet8: class extends self.ISpriteInstance {},
	EnemyHeart2: class extends self.ISpriteInstance {},
	EnemyBullet9: class extends self.ISpriteInstance {},
	AkumuBattleSpotlight: class extends self.ISpriteInstance {},
	PongPointCount: class extends self.ISpriteFontInstance {},
	PlayerPong: class extends self.ISpriteInstance {},
	EnemyPong: class extends self.ISpriteInstance {},
	PongBullet: class extends self.ISpriteInstance {},
	pointforplayer: class extends self.ISpriteInstance {},
	pointforenemy: class extends self.ISpriteInstance {},
	EnemyHeart3: class extends self.ISpriteInstance {},
	TurArrowUp: class extends self.ISpriteInstance {},
	TurArrowDown: class extends self.ISpriteInstance {},
	TurArrowRight: class extends self.ISpriteInstance {},
	TurArrowLeft: class extends self.ISpriteInstance {},
	EnemyBullet10: class extends self.ISpriteInstance {},
	EnemyBullet11: class extends self.ISpriteInstance {},
	EnemyBullet12: class extends self.ISpriteInstance {},
	EnemyBullet13: class extends self.ISpriteInstance {},
	BattleTXT2: class extends self.ISpriteFontInstance {},
	EnemyBullet14: class extends self.ISpriteInstance {},
	PongBullet2: class extends self.ISpriteInstance {},
	greenshield: class extends self.ISpriteInstance {},
	EnemyBullet15: class extends self.ISpriteInstance {},
	Aimer2: class extends self.ISpriteInstance {},
	AkumuBattleSpotlight2: class extends self.ISpriteInstance {},
	EnemyBullet16: class extends self.ISpriteInstance {},
	TurArrowDown2: class extends self.ISpriteInstance {},
	TurArrowLeft2: class extends self.ISpriteInstance {},
	TurArrowRight2: class extends self.ISpriteInstance {},
	TurArrowUp2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Door: class extends self.ISpriteInstance {},
	Trigger: class extends self.ISpriteInstance {},
	Border: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Warp: class extends self.ISpriteInstance {},
	sweetSand: class extends self.IParticlesInstance {},
	WcDonaldsBKG: class extends self.ISpriteInstance {},
	feathers: class extends self.IParticlesInstance {},
	FurryWorldBKG: class extends self.ISpriteInstance {},
	AlliumPic: class extends self.ISpriteInstance {},
	huxleyparticles: class extends self.IParticlesInstance {},
	Particles: class extends self.IParticlesInstance {},
	centerbox: class extends self.ISpriteInstance {},
	darkspotlight: class extends self.ISpriteInstance {},
	darkgradient: class extends self.ISpriteInstance {},
	arcade: class extends self.ISpriteInstance {},
	REDDEATH: class extends self.ISpriteInstance {},
	original: class extends self.ISpriteInstance {},
	deltaexplosion: class extends self.ISpriteInstance {},
	ElyssaRoomBKG: class extends self.ISpriteInstance {},
	catbed: class extends self.ISpriteInstance {},
	PingPongTable: class extends self.ISpriteInstance {},
	PingPongBKG: class extends self.ISpriteInstance {},
	CafeteriaTables: class extends self.ISpriteInstance {},
	MessHallTable: class extends self.ISpriteInstance {},
	toaster: class extends self.ISpriteInstance {},
	evildeathbattle: class extends self.ISpriteInstance {},
	deadcloversigilbook: class extends self.ISpriteInstance {},
	holeinwall: class extends self.ISpriteInstance {},
	holeinwall2: class extends self.ISpriteInstance {},
	tallgrass: class extends self.ISpriteInstance {},
	LaserLine: class extends self.ISpriteInstance {},
	trashcan: class extends self.ISpriteInstance {},
	toilet: class extends self.ISpriteInstance {},
	LaserLine2: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	knive: class extends self.ISpriteInstance {}
}